### PR TITLE
fix(logging): correct error logging to display error message

### PR DESCRIPTION
**Pull request by LumixximuL**
Signed-off-by: Taylor Webber <taylor.j.webber@gmail.com>

Error message is not correctly being displayed on failure

## AWS Producer error message
Screen Shot 2022-12-29 at 10 30 46 PM

## Dynamic Secret error message
Screen Shot 2022-12-29 at 10 31 20 PM

### CODE REVIEW

**Comment by LumixximuL** [comment]
@LanceMcCarthy could this get reviewed when you get a chance?

**Comment by LanceMcCarthy** [comment]
I'll check it out today, thanks for grabbing the details.

**Comment by LanceMcCarthy** [comment]
Thank you for @ mentioning me. I never got the original notification. I was shocked to see all the pending PRs.

Your PR is merged now, but I'll be doing the rest of the dependabot items this morning, once that is done, I'll push out an update to v3

Worst-case scenario, if there's a breaking change in the upstream SDK update, I'll release a v4 and also backport your fixes to v3.

**Comment by LanceMcCarthy** [comment]
@LumixximuL All set, `v3.0.2` has been published (the `v3` tag has been fast-forwarded, too)

Please let me know if you have any problems!

**Comment by LumixximuL** [comment]
Thanks so much @LanceMcCarthy !!

**Pull request merged**
